language: node_js
node_js:
  - "8"
cache: yarn
script:
  - yarn run prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public/
  target_branch: gh-pages
  on:
    branch: master